languageCode = "en-us"
title = "SiteNam"
baseurl = "https://rdwatters.github.io/hugo-console"
publishDir = "docs"

[taxonomies]
	tag = "tags"
	category = "categories"

[params]
	examplebaseurl = "http://yoursite.com"
